spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review_portal
    username: root
    password: Pass@123
  jpa:
    show-sql: true
    foramt-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  application:
    name: JPADemo2
  